- hosts: all
  vars:
    deploy_folder: /home/ubuntu/pro-cargo/pro-cargo

  tasks:
    - name: Run yarn install
      shell: docker run --rm --network pro-cargo -v {{ deploy_folder }}:/app -w /app node:16 bash -c "yarn install"

    - name: Run migration
      shell: docker run --rm --network pro-cargo -v {{ deploy_folder }}:/app -w /app node:16 bash -c "yarn migration:run"
